name: flutter_rick_and_morty
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.0.1
  http: ^0.13.5
  pretty_dio_logger: ^1.3.1
  get_it: ^7.2.0
  injectable: ^2.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  stream_transform: ^2.1.0
  bloc_concurrency: ^0.2.1
  device_preview: ^1.1.0
  url_launcher: ^6.1.7
  google_fonts: 3.0.1
  shared_preferences: 2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.4
  build_runner: ^2.3.3

flutter:
  uses-material-design: true